name: ChatAutoComplete
description: Auto complete names if prefix @ is used in messages.
author: Neptune Whitebear (Pinkishu @bukkit.org)
version: 0.6.5 Beta
main: plugin.whitebear.neptune.ChatAutoComplete.ChatAutoComplete
softdepend: [Permissions]

permissions:
    autocomp.autocomp:
        default: true
        description: Allows to use autocomplete.