name: ChatAutoComplete
description: Auto complete names if prefix @ is used in messages.
version: 0.5 Beta
main: plugin.whitebear.neptune.ChatAutoComplete.ChatAutoComplete

permissions:
    autocomp.autocomp:
        default: true
        description: Allows to use autocomplete.