name: ChatAutoComplete
description: Auto complete names if prefix @ is used in messages.
author: Neptune Whitebear (Pinkishu @bukkit.org)
version: 0.6.5 Beta
main: de.neptune_whitebear.ChatAutoComplete.ChatAutoComplete
softdepend: [Permissions, Spout]

permissions:
    autocomp.autocomp:
        default: true
        description: Allows to use autocomplete.